import { Container, Typography } from "@mui/material";

export default function LeftDownArticle() {
  return (
    <Container sx={{backgroundColor: "#e6e4e4", zIndex: "1", marginLeft: "80px"}} disableGutters>
      <Typography variant="h5" sx={{lineHeight: "1.6"}}>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis enim, excepturi non officia quia autem ad cum numquam debitis veritatis hic quam unde facilis, neque itaque quasi at impedit nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quibusdam consequatur exercitationem ipsum suscipit maxime tempore velit delectus hic accusantium, repellendus doloribus, quisquam architecto minima labore laborum natus iure amet! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nesciunt commodi, dolor natus accusamus voluptate in autem quam deserunt, eum, cumque vitae beatae! Perspiciatis nulla quaerat iste distinctio odio tempore ab. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio tempora ullam, autem minus nemo ad accusantium beatae commodi labore, adipisci, obcaecati impedit vero quae optio dignissimos provident. Repellendus, dicta beatae?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis enim, excepturi non officia quia autem ad cum numquam debitis veritatis hic quam unde facilis, neque itaque quasi at impedit nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quibusdam consequatur exercitationem ipsum suscipit maxime tempore velit delectus hic accusantium, repellendus doloribus, quisquam architecto minima labore laborum natus iure amet! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nesciunt commodi, dolor natus accusamus voluptate in autem quam deserunt, eum, cumque vitae beatae! 
        
        Perspiciatis nulla quaerat iste distinctio odio tempore ab. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio tempora ullam, autem minus nemo ad accusantium beatae commodi labore, adipisci, obcaecati impedit vero quae optio dignissimos provident. Repellendus, dicta beatae?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis enim, excepturi non officia quia autem ad cum numquam debitis veritatis hic quam unde facilis, neque itaque quasi at impedit nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quibusdam consequatur exercitationem ipsum suscipit maxime tempore velit delectus hic accusantium, repellendus doloribus, quisquam architecto minima labore laborum natus iure amet! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nesciunt commodi, dolor natus accusamus voluptate in autem quam deserunt, eum, cumque vitae beatae! Perspiciatis nulla quaerat iste distinctio odio tempore ab. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio tempora ullam, autem minus nemo ad accusantium beatae commodi labore, adipisci, obcaecati impedit vero quae optio dignissimos provident. Repellendus, dicta beatae?
      </Typography>
    </Container>
  );
}